# Generated by Django 5.1.2 on 2024-11-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IPCSections',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section_number', models.CharField(max_length=10, unique=True)),
                ('description', models.TextField()),
            ],
        ),
    ]
