# Generated by Django 5.1.2 on 2024-11-15 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcsections',
            name='offense',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='ipcsections',
            name='description',
            field=models.TextField(default=''),
        ),
    ]
