# Generated by Django 5.1.2 on 2024-11-15 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0002_ipcsections_offense_alter_ipcsections_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipcsections',
            name='punishment',
            field=models.TextField(default=''),
        ),
    ]
