# Generated by Django 5.1.2 on 2024-11-15 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0003_ipcsections_punishment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipcsections',
            name='section_number',
            field=models.CharField(max_length=10),
        ),
    ]
