# Generated by Django 5.1.2 on 2024-11-25 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0004_alter_ipcsections_section_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityQuestions',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
        ),
    ]
