# Generated by Django 5.1.2 on 2024-11-25 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0005_communityquestions'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommunityAnswers',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ipc.communityquestions')),
            ],
        ),
    ]
