# Generated by Django 5.1.2 on 2024-11-25 12:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0006_communityanswers'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityanswers',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='communityquestions',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
