# Generated by Django 5.1.2 on 2024-11-25 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0007_communityanswers_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityanswers',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityanswers',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityquestions',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='communityquestions',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
