# Generated by Django 5.1.2 on 2024-11-25 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0008_communityanswers_dislikes_communityanswers_likes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='communityanswers',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='communityquestions',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
