# Generated by Django 5.1.2 on 2024-11-25 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipc', '0010_answerlike_questionlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='answerlike',
            name='vote_type',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='questionlike',
            name='vote_type',
            field=models.IntegerField(default=1),
        ),
    ]
